[theme]
base = "dark"
primaryColor = "#ec7e04"
backgroundColor = "#092c73"
secondaryBackgroundColor = "#0b1d42"
textColor = "#e8ecf4"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
