MAPBOX_API_KEY = "pk.eyJ1IjoibHVjaWFub2NlYiIsImEiOiJjbW5xNDdkbnQwM2k1MndvZHQ5czMyamwyIn0.xFDXbBLCiQOyCmTYD87gDg"
 
 
[USERS.5257]
password = "pass1"
franquicia = "5257"
 
[USERS.4444]
password = "pass2"
franquicia = "4444"
 
[USERS.3183]
password = "pass3"
franquicia = "3183"
 
[USERS.4340]
password = "pass4"
franquicia = "4340"
 
[USERS.3974]
password = "pass5"
franquicia = "3974"
 
[USERS.3008]
password = "pass6"
franquicia = "3008"
 
[USERS.4544]
password = "pass7"
franquicia = "4544"
 
[USERS.admin]
password = "admin_pass"
franquicia = "todas"